:stem: latexmath
== Layered Standard Manifest File [[layered-standard-manifest-file]]

This layered standard requires the use of a layered standard manifest file and it shall be stored inside the FMU at the following path: `/extra/org.fmi-standard.fmi-ls-dae/fmi-ls-manifest.xml`.

[Add figure here] shows the root element `fmiLayeredStandardManifest`.

Two additional elements - <<AlgebraicVariables>> and <<ModelStructure>> - are included in the layered standard manifest file to describe the DAE formulation.

.`fmiModelDescription` element details.
[[table-schema-fmiModelDescription]]
[cols="1,3",options="header"]
|====
|Element
|Description

|<<AlgebraicVariables>>
|List of all <<AlgebraicVariable, algebraic variables>> exposed for the DAE formulation.

|<<ModelStructure>>
|Defines the structure of the DAE formulation for the model.
Especially, the ordered lists of https://fmi-standard.org/docs/3.0.2/#output[outputs], continuous-time https://fmi-standard.org/docs/3.0.2/#state[state], and the initial unknowns (the unknowns during https://fmi-standard.org/docs/3.0.2/#InitializationMode[InitializationMode]) are *re*-defined and overwrite the corresponding https://fmi-standard.org/docs/3.0.2/#ModelStructure[ModelStructure] present in the `modelDescription.xml`, with the addition of the  <<Residual, residuals>> element.
The <<AlgebraicVariables,algebraic variables>> can now also be included as dependencies.

|<<Annotations>>
|Optional annotations for the top-level element.

|====

The XML attributes of `<fmiLayeredStandardManifest>` are:

.`<fmiLayeredStandardManifest>`` attribute details.
[[table-schema-fmi-ls-dae-attributes]]
[cols="1,1,1,2",options="header"]
|====
|Attribute
|Namespace
|Value
|Description

|`fmi-ls-name`
|`\http://fmi-standard.org/fmi-ls-manifest`
|`org.fmi-standard.fmi-ls-dae`
|Name of the layered standard in reverse domain name notation.

|`fmi-ls-version`
|`\http://fmi-standard.org/fmi-ls-manifest`
|`0.0.1`
|Version of the layered standard. This layered standard uses semantic versioning, as defined in <<PW13>>.

|`fmi-ls-description`
|`\http://fmi-standard.org/fmi-ls-manifest`
|`Layered standard for DAE support in FMI`
|String with a brief description of the layered standard that is suitable for display to users.
|====

=== Algebraic variables [[AlgebraicVariables, `<AlgebraicVariables>`]]

The element <<AlgebraicVariables>> defines the list of the algebraic variables.

.AlgebraicVariables elements.
[[table-algebraic-variables-details]]
[cols="1,5a", options="header"]
|====
|Element
|Description

|`AlgebraicVariable`
|An <<AlgebraicVariable>> present in the `ModelVariables` element of the modelDescription.xml.
|====

[[AlgebraicVariable, `<AlgebraicVariable>`]]
Each <<AlgebraicVariable>> has only one attribute defining the value reference.

.Attributes to <<AlgebraicVariable>> element.
[[table-alg-details]]
[cols="1,5a", options="header"]
|====
|Attribute
|Description

|`valueReference`
|The value reference for the algebraic variable present in the `ModelVariables` of the modelDescription.xml.
|====

=== Model Structure [[ModelStructure,`<ModelStructure>`]]

The structure of the model for the DAE-formulation is defined in element <<ModelStructure>>.
It defines the <<model-dependencies,dependencies>> between variables.
The <<ModelStructure>> element is extended with an additional element - <<Residual>> - and the optional dependencies can now include algebraic variables.

An FMU that follows this layered standard must expose all residuals with the <<Residual>>.

NOTE: The <<ModelStructure>> defined here extends the one from the core FMI standard.
All elements defined there (`Output`, `ContinuousStateDerivative`, `ClockedState`, `InitialUnknown`, `EventIndicator`) retain their existing semantics, with the addition that each element's `dependencies` attribute may now also reference <<AlgebraicVariable, algebraic variables>>.

The <<ModelStructure>> element is extended with one additional element, <<Residual>>, described below.

.Additional ModelStructure element.
[#table-model-structure-dae-element]
[cols="1,5a",options="header"]
|====
|Element
|Description

|`Residual`
|[[Residual,`<Residual>`]]
Ordered list of residual equations (constraints).
Each `<Residual>` contains one or more `<<Formulation>>` child elements.
When a single `<Formulation>` is present, it defines the residual equation directly.
When multiple `<Formulation>` elements are present within the same `<Residual>`, they represent the same constraint differentiated to successive orders.
This grouping tells the importer that the equations are structurally related, which can e.g. be used to perform index reduction with dummy derivatives or projection methods.
Note that each formulation inside one residual element must reference unique variables in the FMU.

The functional dependency is defined as: +
latexmath:[{0 := \mathbf{f}_{\mathit{res}}(\mathbf{x}_c, \mathbf{z}_c, \mathbf{u}_c, t, \mathbf{p})}]
|====

==== Formulation [[Formulation, `<Formulation>`]]

Each `<<Formulation>>` element within a `<<Residual>>` has the following attributes:

.Attributes to `<<Formulation>>` element.
[[table-formulation-details]]
[cols="1,5a", options="header"]
|====
|Attribute
|Description

|`valueReference`
|The value reference of the residual variable latexmath:[{v_{\mathit{unknown}}}], which must be present in the `ModelVariables` element of the `modelDescription.xml`.

|`index`
|[[index-formulation]]
Optional attribute indicating the DAE index of the original constraint, i.e., how many times this particular equation must be differentiated in order to solve for a particular derivative.

|`dependencies`
|[[model-dependencies]]
Optional attribute defining the algebraic dependencies as a list of value references of the knowns latexmath:[{\mathbf{v}_{\mathit{known}}}] that this formulation directly depends on.

Knowns latexmath:[{\mathbf{v}_{\mathit{known}}}] in https://fmi-standard.org/docs/3.0.2/#table-math-model-exchange[ContinuousTimeMode] (ME) for `<<Formulation>>` elements are: +

* inputs (variables with https://fmi-standard.org/docs/3.0.2/#causality[causality] = https://fmi-standard.org/docs/3.0.2/#input[input]),

* continuous states,

* continuous state derivatives,

* parameters (variables with https://fmi-standard.org/docs/3.0.2/#causality[causality] = https://fmi-standard.org/docs/3.0.2/#parameter[parameter]),

* algebraic variables (variables listed in the `<<AlgebraicVariables>>` element),

* https://fmi-standard.org/docs/3.0.2/#independent[independent] variable (usually time; https://fmi-standard.org/docs/3.0.2/#causality[causality] = https://fmi-standard.org/docs/3.0.2/#independent[independent]).

If `dependencies` is not present, it must be assumed that the formulation depends on all knowns.
If `dependencies` is present as an empty list, the formulation depends on none of the knowns.
Otherwise the formulation depends on the knowns defined by the given value references.

|`dependenciesKind`
|See the description of https://fmi-standard.org/docs/3.0.2/#dependenciesKind[`dependenciesKind`] in the core FMI standard.
TODO: Extend to help importer?
|====

=== Annotations

NOTE: TODO

---

=== Getting Partial Derivatives

The partial derivative API functions https://fmi-standard.org/docs/3.0.2/#fmi3GetDirectionalDerivative[fmi3GetDirectionalDerivative] and https://fmi-standard.org/docs/3.0.2/#fmi3GetAdjointDerivative[fmi3GetAdjointDerivative] are used as defined in the core FMI standard, with the following extensions for DAE FMUs:

* Algebraic variables (variables listed in `<<AlgebraicVariables>>`) may appear as knowns for any unknown.
* When the unknown is a <<Formulation>> in a <<Residual>>(i.e., a residual variable), continuous state derivatives may additionally appear as knowns.

=== Hello World DAE Example

Below outlines how to map the different forms of the Hello World DAE Example to the manifest file detailed here.

==== Hello World DAE - Fully-Implicit DAE

The fully-implicit representation

[latexmath]
++++
F(\dot{x}, x, t) = 0
++++

is given by

[latexmath]
++++
F: \mathbb{R}^3 \times \mathbb{R}^3 \times \mathbb{R} \to \mathbb{R}^3,
\begin{pmatrix}
x \\
\dot{x} \\
t
\end{pmatrix}
\mapsto
\begin{pmatrix}
F_1 \\
F_2 \\
F_3
\end{pmatrix}
=
\begin{pmatrix}
\dot{x_1}   - x_2   \\
x_2 + 2 x_3 - x_1   \\
x_2 - 3 x_3 - 2 x_1
\end{pmatrix}
++++

Assume the FMU has these variables:

[cols="1,1", options="header"]
|====
|Variable | valueReference
|latexmath:[t] | 1
|latexmath:[x_1] | 2
|latexmath:[x_2] | 3
|latexmath:[x_3] | 4
|latexmath:[\dot{x_1}] | 5
|latexmath:[\dot{x_2}] | 6
|latexmath:[\dot{x_3}] | 7
|latexmath:[F_1] | 8
|latexmath:[F_2] | 9
|latexmath:[F_3] | 10
|====

In this case `x_2` and `x_3` do not appear differentiated in any equations, hence they are classified as algebraic (element of `<<AlgebraicVariables>>`).
An example of the `<<AlgebraicVariables>>` and `<<ModelStructure>>` elements would be:

```xml
<AlgebraicVariables>
  <AlgebraicVariable valueReference="3"/> <!-- x_2 -->
  <AlgebraicVariable valueReference="4"/> <!-- x_3 -->
</AlgebraicVariables>
<ModelStructure>
  <Residual> <!-- F1 -->
    <Formulation
      valueReference="8"
      dependencies="5 3"
      dependenciesKind="fixed fixed"/>
  </Residual>
  <Residual> <!-- F2 -->
    <Formulation
      valueReference="9"
      dependencies="2 3 4"
      dependenciesKind="fixed fixed fixed"/>
  </Residual>
  <Residual> <!-- F3 -->
    <Formulation
      valueReference="10"
      dependencies="2 3 4"
      dependenciesKind="fixed fixed fixed"/>
  </Residual>
</ModelStructure>
```
NOTE: The derivatives of `x_1`, `x_2`, and `x_3` (`\dot{x_1}`, `\dot{x_2}`, `\dot{x_3}`) are still noted with the `derivative` attribute under the `ModelVariables` element, which gives the importer all the information they need to solve the equations.

==== Hello World DAE - Semi-Explicit DAE

The semi-explicit representation

[latexmath]
++++
\begin{split}
\dot{x} & = f(x, y, t) \\
      0 & = g(x, y, t)
\end{split}
++++

is given by

[latexmath]
++++
\begin{split}
f: \mathbb{R} \times \mathbb{R}^2 \times \mathbb{R} \to \mathbb{R}, \;
&(x,y,t) \mapsto
\begin{pmatrix}
y_1
\end{pmatrix}
 \\
g: \mathbb{R} \times \mathbb{R}^2 \times \mathbb{R} \to \mathbb{R}, \;
&(x,y,t) \mapsto
\begin{pmatrix}
y_1 + 2 y_2 - x   \\
y_1 - 3 y_2 - 2 x
\end{pmatrix}
\end{split}
++++

Assume the FMU has the following variables:

[cols="1,1", options="header"]
|====
|Variable | valueReference
|latexmath:[t] | 1
|latexmath:[x] | 2
|latexmath:[y_1] | 3
|latexmath:[y_2] | 4
|latexmath:[\dot{x}] | 5
|latexmath:[g_1] | 6
|latexmath:[g_2] | 7
|====

This case contains the same algebraic variables.
However this time the the derivative of `x` is given in explicit form in the `ModelStructure`:

```xml
<AlgebraicVariables>
  <AlgebraicVariable valueReference="3"/> <!-- y1 -->
  <AlgebraicVariable valueReference="4"/> <!-- y2 -->
</AlgebraicVariables>

<ModelStructure>
  <ContinuousStateDerivative
    valueReference="5"
    dependencies="3"
    dependenciesKind="fixed"/> <!-- dot(x) = y1 -->
  <Residual> <!-- g1: y1 + 2*y2 - x = 0 -->
    <Formulation
      valueReference="6"
      dependencies="2 3 4"
      dependenciesKind="fixed fixed fixed"/>
  </Residual>
  <Residual> <!-- g2: y1 - 3*y2 - 2*x = 0 -->
    <Formulation
      valueReference="7"
      dependencies="2 3 4"
      dependenciesKind="fixed fixed fixed"/>
  </Residual>
</ModelStructure>
```

==== Hello World DAE - Explicit ODE

This simple system could also be transformed into an explicit ODE formulation

[latexmath]
++++
\begin{split}
\dot{x} &= \frac{7}{5}x
\end{split}
++++

with local variables latexmath:[y] and latexmath:[z]

[latexmath]
++++
\begin{split}
y       &= \frac{7}{5}x   \\
z       &= -\frac{x}{5}
\end{split}
++++

and exported as an ODE ModelExchange FMU:

[cols="1,1", options="header"]
|====
|Variable | valueReference
|latexmath:[t] | 1
|latexmath:[x] | 2
|latexmath:[y] | 3
|latexmath:[z] | 4
|latexmath:[\dot{x}] | 5
|====

This would correspond to the regular ODE ModelStructure:

```xml
<ModelStructure>
  <ContinuousStateDerivative <!-- dot(x) = 7/5 * x -->
    valueReference="5"
    dependencies="2"
    dependenciesKind="fixed"/>
</ModelStructure>
```

=== Example 2 (differentiated formulations)

Consider the following index 2 DAE system:

latexmath:[r_1 = C_1\frac{dx_1}{dt} + y = 0]

latexmath:[r_2 = C_2\frac{dx_2}{dt} - y + 1 = 0]

latexmath:[r_3 = x_1 - x_2 = 0]

Assume it is exported as a DAE FMU with the following variables:

[cols="1,1", options="header"]
|====
|Variable | valueReference
|latexmath:[x_1] | 1
|latexmath:[x_2] | 2
|latexmath:[y] | 3
|latexmath:[\frac{dx_1}{dt}] | 4
|latexmath:[\frac{dx_2}{dt}] | 5
|latexmath:[r_1] | 6
|latexmath:[r_2] | 7
|latexmath:[r_3] | 8
|latexmath:[\frac{dr_3}{dt}] | 9
|====

**Case 1:**
No structural analysis.
The importer is responsible to figure out how to solve the system:

```xml
<ModelStructure>
  <Residual> <!-- r1 -->
    <Formulation
      valueReference="6"
      dependencies="3 4"
      dependenciesKind="dependent dependent"/>
  </Residual>
  <Residual> <!-- r2 -->
    <Formulation
      valueReference="7"
      dependencies="3 5"
      dependenciesKind="dependent dependent"/>
  </Residual>
  <Residual> <!-- r3 -->
    <Formulation
      valueReference="8"
      dependencies="1 2"
      dependenciesKind="dependent dependent"/>
  </Residual>
</ModelStructure>
```

**Case 2:**
The FMU additionally indicates that latexmath:[r_3] is a constraint of index 2, i.e., it must be differentiated twice to obtain an index 1 system.
This gives the importer structural information to know to apply a solver able to handle index 2 problems:

```xml
<ModelStructure>
  <Residual> <!-- r1 -->
    <Formulation
      valueReference="6"
      dependencies="3 4"
      dependenciesKind="dependent dependent"/>
  </Residual>
  <Residual> <!-- r2 -->
    <Formulation
      valueReference="7"
      dependencies="3 5"
      dependenciesKind="dependent dependent"/>
  </Residual>
  <Residual> <!-- r3, index=2 signals this constraint needs 2 differentiations -->
    <Formulation
      index="2"
      valueReference="8"
      dependencies="1 2"
      dependenciesKind="dependent dependent"/>
  </Residual>
</ModelStructure>
```

**Case 3:**
The FMU exposes both latexmath:[r_3] and its time derivative latexmath:[\dot{r}_3] grouped within the same `<Residual>`, which indicates that these are the original constraint and its differentiated form.
The importer can use this grouping to apply the dummy derivatives algorithm or use latexmath:[r_3] as a drift-correction projection when integrating the index 1 formulation:

latexmath:[r_3 = x_1 - x_2 = 0]

latexmath:[\dot{r}_3 = \frac{dx_1}{dt} - \frac{dx_2}{dt} = 0]
```xml
<ModelStructure>
  <Residual> <!-- r1 -->
    <Formulation
      valueReference="6"
      dependencies="3 4"
      dependenciesKind="dependent dependent"/>
  </Residual>
  <Residual> <!-- r2 -->
    <Formulation
      valueReference="7"
      dependencies="3 5"
      dependenciesKind="dependent dependent"/>
  </Residual>
  <Residual> <!-- r3 and its derivative, grouped as related formulations -->
    <Formulation
      index="2"
      valueReference="8"
      dependencies="1 2"
      dependenciesKind="dependent dependent"/> <!-- r3 -->
    <Formulation
      index="1"
      valueReference="9"
      dependencies="4 5"
      dependenciesKind="dependent dependent"/> <!-- der(r3) -->
  </Residual>
</ModelStructure>
```

The API for partial derivative, `GetDirectionalDerivative` and/or `GetAdjointDerivative` could be used with this structure to apply the dummy derivatives algorithm, or the index 2 constraint can serve as a projection constraint when integrating the index 1 formulation.
